name: brainkick
description: A duel-style party game.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  event_bus: ^2.0.0
  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/cards/
    - assets/images/home.png
    - assets/packs/pack_1/
    - assets/packs/pack_2/
    - assets/packs/pack_3/
  fonts:
    - family: StudentsTeacher
      fonts:
        - asset: assets/fonts/TheStudentsTeacher-Regular.ttf
    - family: AlteHaasGrotesk
      fonts:
        - asset: assets/fonts/AlteHaasGroteskRegular.ttf
        - asset: assets/fonts/AlteHaasGroteskBold.ttf