name: application
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/lightning.png
    - assets/images/pingpong.png 
    - assets/images/fire.png 
    - assets/text/fire.txt
    - assets/text/pingpong.txt
    - assets/text/lightning.txt
  fonts:
    - family: StudentsTeacher
      fonts:
        - asset: assets/fonts/TheStudentsTeacher-Regular.ttf